version: '3'
services:
  react-web:
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /usr/app/node_modules
      - .:/usr/app
